In [2]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import files
upload = files.upload()

Saving Advertisement Sale Prediction From an Existing Customer.xlsx to Advertisement Sale Prediction From an Existing Customer.xlsx


**LOAD** **DATASET**

In [3]:
df = pd.read_excel("Advertisement Sale Prediction From an Existing Customer.xlsx")
df

AGE  SALARY  PURCHASE STATUS
0     19   12439                0
1     23   34642                1
2     23   17790                1
3     19   34282                0
4     19   38039                1
..   ...     ...              ...
113   73   39951                0
114   76   37607                1
115   80   47417                0
116   71   48965                0
117   75   32745                0

[118 rows x 3 columns]

**SUMMARIRIZE DATASET**

In [8]:
df.head()

AGE  SALARY  PURCHASE STATUS
0   19   12439                0
1   23   34642                1
2   23   17790                1
3   19   34282                0
4   19   38039                1

In [10]:
df.describe()

AGE        SALARY  PURCHASE STATUS
count  118.000000    118.000000       118.000000
mean    42.771186  49103.745763         0.525424
std     18.564008  20949.837136         0.501483
min     18.000000   8348.000000         0.000000
25%     28.000000  32769.250000         0.000000
50%     38.000000  46139.500000         1.000000
75%     58.750000  66965.750000         1.000000
max     80.000000  96922.000000         1.000000

**Segregate Dataset into X(input/IndependentVariable)& Y(Output/DependentVariable)**

In [4]:
x = df.iloc[:,:-1].values
x

array([[   19, 12439],
       [   23, 34642],
       [   23, 17790],
       [   19, 34282],
       [   19, 38039],
       [   24, 24678],
       [   18, 29232],
       [   19, 17241],
       [   25, 19830],
       [   24, 21178],
       [   19,  9040],
       [   20,  8451],
       [   18, 23650],
       [   22, 15418],
       [   24, 32158],
       [   24, 28123],
       [   25, 31198],
       [   24,  8348],
       [   24, 18314],
       [   22, 32558],
       [   25, 29355],
       [   20, 28149],
       [   21, 37241],
       [   24, 12012],
       [   19, 31889],
       [   28, 31623],
       [   35, 46246],
       [   35, 72320],
       [   33, 47254],
       [   29, 42374],
       [   38, 47074],
       [   28, 67045],
       [   31, 28641],
       [   30, 32712],
       [   29, 66377],
       [   35, 34504],
       [   37, 41329],
       [   31, 28118],
       [   27, 28767],
       [   29, 79165],
       [   26, 67860],
       [   27, 66441],
       [   29, 74538],
       [   

In [5]:
y = df.iloc[:,-1].values
y

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0])

**Splittimg Dataset into Train & Test**

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state = 0)

**Feature Scaling**
We scale our data to make all the features contribute equally to the result

Fit_Transform - fit methodis calculating the mean and the variance of each of the features present in our data

Transform  - this method is transforming all the features using the respective mean and variancd,

we want our test data to be a completely new and surprise set for our model

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[-0.27317236, -0.44595046],
       [ 0.37073391,  1.83310278],
       [-0.7024432 ,  0.92742355],
       [-0.80976091,  1.35171796],
       [-1.29269062, -0.74902483],
       [ 1.6048876 ,  1.62537329],
       [-1.34634947, -0.9941835 ],
       [-0.48780778,  0.25059144],
       [ 1.65854645,  0.39579333],
       [ 0.04878078, -0.01602468],
       [ 1.65854645, -0.36968427],
       [-0.54146664,  1.37832131],
       [ 1.6048876 , -0.37041246],
       [ 0.90732247, -0.43832869],
       [-0.43414892,  1.09757823],
       [-1.02439634, -1.52421169],
       [-1.23903176, -2.00302356],
       [-0.91707863,  0.18282084],
       [ 1.39025217, -0.89922699],
       [ 1.12195789,  1.13986203],
       [ 0.69268705,  1.98223693],
       [-0.7024432 , -1.17501836],
       [-1.07805519, -0.73154817],
       [ 0.96098133,  1.10524854],
       [-0.75610206,  1.20525386],
       [-0.86341977,  0.8121747 ],
       [-1.29269062, -0.56663649],
       [-1.02439634, -1.04802131],
       [-1.02439634,

**Training**

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(x_train,y_train)

LogisticRegression(random_state=0)

*Predicting, whether new customer with Age And Salary will Buy or Not*

In [16]:
age = int(input("age"))
salary = int(input("Salary"))
newCust = [[age,salary]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will Buy the Product")
else:
  print("Customer will Not Buy the Product")

age25
Salary8000
[0]
Customer will Not Buy the Product


**Prediction For All The Test Data*

In [17]:
y_pred = model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]]


**Accurecy And Confusion Matrix**

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix : ")
print(cm)

print("Accuracy of the Model : {0}%".format(accuracy_score(y_test , y_pred)*100))

Confusion Matrix : 
[[18  0]
 [12  0]]
Accuracy of the Model : 60.0%
